/*
 *  Copyright (C) 2020 TechNexion Ltd.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */


#ifndef __AXONFABRIC_NXBOX_PINS_H
#define __AXONFABRIC_NXBOX_PINS_H


#include <linux/pinctrl/pinctrl.h>
#include <linux/pinctrl/pinctrl-axonfabric.h>

#define AXONF_PIN_F_GPIO01 	0
#define AXONF_PIN_F_GPIO02 	1
#define AXONF_PIN_F_GPIO03 	2
#define AXONF_PIN_F_GPIO04 	3
#define AXONF_PIN_F_GPIO05 	4
#define AXONF_PIN_F_GPIO06 	5
#define AXONF_PIN_F_GPIO07 	6
#define AXONF_PIN_F_GPIO08 	7
#define AXONF_PIN_F_GPIO09 	8
#define AXONF_PIN_F_GPIO10 	9
#define AXONF_PIN_F_GPIO11 	10
#define AXONF_PIN_F_GPIO12 	11
#define AXONF_PIN_F_GPIO13 	12
#define AXONF_PIN_F_GPIO14 	13
#define AXONF_PIN_F_GPIO15 	14
#define AXONF_PIN_F_GPIO16 	15
#define AXONF_PIN_F_GPIO17 	16
#define AXONF_PIN_F_GPIO18 	17
#define AXONF_PIN_F_GPIO19 	18
#define AXONF_PIN_F_GPIO20 	19
#define AXONF_PIN_F_GPIO21 	20
#define AXONF_PIN_F_GPIO22 	21
#define AXONF_PIN_F_GPIO23 	22
#define AXONF_PIN_F_GPIO24 	23
#define AXONF_PIN_F_GPIO25 	24
#define AXONF_PIN_F_GPIO26 	25
#define AXONF_PIN_F_GPIO27 	26
#define AXONF_PIN_F_GPIO28 	27
#define AXONF_PIN_F_GPIO29 	28
#define AXONF_PIN_F_GPIO30 	29
#define AXONF_PIN_F_GPIO31 	30
#define AXONF_PIN_F_GPIO32 	31
#define AXONF_PIN_F_GPIO33 	32
#define AXONF_PIN_F_GPIO34 	33
#define AXONF_PIN_F_GPIO35 	34
#define AXONF_PIN_F_GPIO36 	35
#define AXONF_PIN_F_GPIO37 	36
#define AXONF_PIN_F_GPIO38 	37
#define AXONF_PIN_F_GPIO39 	38
#define AXONF_PIN_F_GPIO40 	39
#define AXONF_PIN_F_GPIO41 	40
#define AXONF_PIN_F_GPIO42 	41
#define AXONF_PIN_F_GPIO43 	42
#define AXONF_PIN_F_GPIO44 	43
#define AXONF_PIN_F_GPIO45 	44
#define AXONF_PIN_F_GPIO46 	45
#define AXONF_PIN_F_GPIO47 	46
#define AXONF_PIN_F_GPIO48 	47
#define AXONF_PIN_F_GPIO49 	48
#define AXONF_PIN_F_GPIO50 	49
#define AXONF_PIN_F_GPIO51 	50
#define AXONF_PIN_F_GPIO52 	51
#define AXONF_PIN_F_GPIO53 	52
#define AXONF_PIN_F_GPIO54 	53
#define AXONF_PIN_F_GPIO55 	54
#define AXONF_PIN_F_GPIO56 	55
#define AXONF_PIN_F_GPIO57 	56
#define AXONF_PIN_F_GPIO58 	57
#define AXONF_PIN_F_GPIO59 	58
#define AXONF_PIN_F_GPIO60 	59
#define AXONF_PIN_F_GPIO61 	60
#define AXONF_PIN_F_GPIO62 	61
#define AXONF_PIN_F_GPIO63 	62
#define AXONF_PIN_F_GPIO64 	63
#define AXONF_PIN_F_GPIO65 	64
#define AXONF_PIN_F_GPIO66 	65
#define AXONF_PIN_F_GPIO67 	66
#define AXONF_PIN_F_GPIO68 	67
#define AXONF_PIN_F_GPIO69 	68
#define AXONF_PIN_F_GPIO70 	69
#define AXONF_PIN_F_UART_TXD 	72
#define AXONF_PIN_F_UART_RXD 	73
#define AXONF_PIN_F_UART_CTS 	74
#define AXONF_PIN_F_UART_RTS 	75
#define AXONF_PIN_F_GPIO_LED1 	76
#define AXONF_PIN_F_GPIO_LED2 	77
#define AXONF_PIN_F_GPIO_LED3 	78
#define AXONF_PIN_CSI0_RST_N 	80
#define AXONF_PIN_CSI0_PWDN 	81
#define AXONF_PIN_CSI0_PDB 	82
#define AXONF_PIN_CSI0_INT 	83
#define AXONF_PIN_CSI1_RST_N 	84
#define AXONF_PIN_CSI1_PWDN 	85
#define AXONF_PIN_CSI1_PDB 	86
#define AXONF_PIN_CSI1_INT 	87
#define AXONF_PIN_CSI2_RST_N 	88
#define AXONF_PIN_CSI2_PWDN 	89
#define AXONF_PIN_CSI2_PDB 	90
#define AXONF_PIN_CSI2_INT 	91
#define AXONF_PIN_CSI3_RST_N 	92
#define AXONF_PIN_CSI3_PWDN 	93
#define AXONF_PIN_CSI3_PDB 	94
#define AXONF_PIN_CSI3_INT 	95
#define AXONF_PIN_CSI4_RST_N 	96
#define AXONF_PIN_CSI4_PWDN 	97
#define AXONF_PIN_CSI4_PDB 	98
#define AXONF_PIN_CSI4_INT 	99
#define AXONF_PIN_CSI5_RST_N 	100
#define AXONF_PIN_CSI5_PWDN 	101
#define AXONF_PIN_CSI5_PDB 	102
#define AXONF_PIN_CSI5_INT 	103
#define AXONF_PIN_LTE_DISABLE_CTRL 	104
#define AXONF_PIN_LTE_WAKE_AP 	105
#define AXONF_PIN_M2_RTS_N 	106
#define AXONF_PIN_F_SIO_GPO30 	107
#define AXONF_PIN_CASE_OPEN_N 	108
#define AXONF_PIN_F_SOC_COREPOWER_OK 	109
#define AXONF_PIN_F_IGNITION 	110

/* PINCTRL DESC */

static const struct pinctrl_pin_desc axonf_nxbox_pins_desc[] = {
	AXONF_PIN_DESC(F_GPIO01),
	AXONF_PIN_DESC(F_GPIO02),
	AXONF_PIN_DESC(F_GPIO03),
	AXONF_PIN_DESC(F_GPIO04),
	AXONF_PIN_DESC(F_GPIO05),
	AXONF_PIN_DESC(F_GPIO06),
	AXONF_PIN_DESC(F_GPIO07),
	AXONF_PIN_DESC(F_GPIO08),
	AXONF_PIN_DESC(F_GPIO09),
	AXONF_PIN_DESC(F_GPIO10),
	AXONF_PIN_DESC(F_GPIO11),
	AXONF_PIN_DESC(F_GPIO12),
	AXONF_PIN_DESC(F_GPIO13),
	AXONF_PIN_DESC(F_GPIO14),
	AXONF_PIN_DESC(F_GPIO15),
	AXONF_PIN_DESC(F_GPIO16),
	AXONF_PIN_DESC(F_GPIO17),
	AXONF_PIN_DESC(F_GPIO18),
	AXONF_PIN_DESC(F_GPIO19),
	AXONF_PIN_DESC(F_GPIO20),
	AXONF_PIN_DESC(F_GPIO21),
	AXONF_PIN_DESC(F_GPIO22),
	AXONF_PIN_DESC(F_GPIO23),
	AXONF_PIN_DESC(F_GPIO24),
	AXONF_PIN_DESC(F_GPIO25),
	AXONF_PIN_DESC(F_GPIO26),
	AXONF_PIN_DESC(F_GPIO27),
	AXONF_PIN_DESC(F_GPIO28),
	AXONF_PIN_DESC(F_GPIO29),
	AXONF_PIN_DESC(F_GPIO30),
	AXONF_PIN_DESC(F_GPIO31),
	AXONF_PIN_DESC(F_GPIO32),
	AXONF_PIN_DESC(F_GPIO33),
	AXONF_PIN_DESC(F_GPIO34),
	AXONF_PIN_DESC(F_GPIO35),
	AXONF_PIN_DESC(F_GPIO36),
	AXONF_PIN_DESC(F_GPIO37),
	AXONF_PIN_DESC(F_GPIO38),
	AXONF_PIN_DESC(F_GPIO39),
	AXONF_PIN_DESC(F_GPIO40),
	AXONF_PIN_DESC(F_GPIO41),
	AXONF_PIN_DESC(F_GPIO42),
	AXONF_PIN_DESC(F_GPIO43),
	AXONF_PIN_DESC(F_GPIO44),
	AXONF_PIN_DESC(F_GPIO45),
	AXONF_PIN_DESC(F_GPIO46),
	AXONF_PIN_DESC(F_GPIO47),
	AXONF_PIN_DESC(F_GPIO48),
	AXONF_PIN_DESC(F_GPIO49),
	AXONF_PIN_DESC(F_GPIO50),
	AXONF_PIN_DESC(F_GPIO51),
	AXONF_PIN_DESC(F_GPIO52),
	AXONF_PIN_DESC(F_GPIO53),
	AXONF_PIN_DESC(F_GPIO54),
	AXONF_PIN_DESC(F_GPIO55),
	AXONF_PIN_DESC(F_GPIO56),
	AXONF_PIN_DESC(F_GPIO57),
	AXONF_PIN_DESC(F_GPIO58),
	AXONF_PIN_DESC(F_GPIO59),
	AXONF_PIN_DESC(F_GPIO60),
	AXONF_PIN_DESC(F_GPIO61),
	AXONF_PIN_DESC(F_GPIO62),
	AXONF_PIN_DESC(F_GPIO63),
	AXONF_PIN_DESC(F_GPIO64),
	AXONF_PIN_DESC(F_GPIO65),
	AXONF_PIN_DESC(F_GPIO66),
	AXONF_PIN_DESC(F_GPIO67),
	AXONF_PIN_DESC(F_GPIO68),
	AXONF_PIN_DESC(F_GPIO69),
	AXONF_PIN_DESC(F_GPIO70),
	AXONF_PIN_DESC(F_UART_TXD),
	AXONF_PIN_DESC(F_UART_RXD),
	AXONF_PIN_DESC(F_UART_CTS),
	AXONF_PIN_DESC(F_UART_RTS),
	AXONF_PIN_DESC(F_GPIO_LED1),
	AXONF_PIN_DESC(F_GPIO_LED2),
	AXONF_PIN_DESC(F_GPIO_LED3),
	AXONF_PIN_DESC(CSI0_RST_N),
	AXONF_PIN_DESC(CSI0_PWDN),
	AXONF_PIN_DESC(CSI0_PDB),
	AXONF_PIN_DESC(CSI0_INT),
	AXONF_PIN_DESC(CSI1_RST_N),
	AXONF_PIN_DESC(CSI1_PWDN),
	AXONF_PIN_DESC(CSI1_PDB),
	AXONF_PIN_DESC(CSI1_INT),
	AXONF_PIN_DESC(CSI2_RST_N),
	AXONF_PIN_DESC(CSI2_PWDN),
	AXONF_PIN_DESC(CSI2_PDB),
	AXONF_PIN_DESC(CSI2_INT),
	AXONF_PIN_DESC(CSI3_RST_N),
	AXONF_PIN_DESC(CSI3_PWDN),
	AXONF_PIN_DESC(CSI3_PDB),
	AXONF_PIN_DESC(CSI3_INT),
	AXONF_PIN_DESC(CSI4_RST_N),
	AXONF_PIN_DESC(CSI4_PWDN),
	AXONF_PIN_DESC(CSI4_PDB),
	AXONF_PIN_DESC(CSI4_INT),
	AXONF_PIN_DESC(CSI5_RST_N),
	AXONF_PIN_DESC(CSI5_PWDN),
	AXONF_PIN_DESC(CSI5_PDB),
	AXONF_PIN_DESC(CSI5_INT),
	AXONF_PIN_DESC(LTE_DISABLE_CTRL),
	AXONF_PIN_DESC(LTE_WAKE_AP),
	AXONF_PIN_DESC(M2_RTS_N),
	AXONF_PIN_DESC(F_SIO_GPO30),
	AXONF_PIN_DESC(CASE_OPEN_N),
	AXONF_PIN_DESC(F_SOC_COREPOWER_OK),
	AXONF_PIN_DESC(F_IGNITION),
};


/* GPIO groups */

static const char * const axonf_nxbox_gpio_groups[] = {
	"F_GPIO01",
	"F_GPIO02",
	"F_GPIO03",
	"F_GPIO04",
	"F_GPIO05",
	"F_GPIO06",
	"F_GPIO07",
	"F_GPIO08",
	"F_GPIO09",
	"F_GPIO10",
	"F_GPIO11",
	"F_GPIO12",
	"F_GPIO13",
	"F_GPIO14",
	"F_GPIO15",
	"F_GPIO16",
	"F_GPIO17",
	"F_GPIO18",
	"F_GPIO19",
	"F_GPIO20",
	"F_GPIO21",
	"F_GPIO22",
	"F_GPIO23",
	"F_GPIO24",
	"F_GPIO25",
	"F_GPIO26",
	"F_GPIO27",
	"F_GPIO28",
	"F_GPIO29",
	"F_GPIO30",
	"F_GPIO31",
	"F_GPIO32",
	"F_GPIO33",
	"F_GPIO34",
	"F_GPIO35",
	"F_GPIO36",
	"F_GPIO37",
	"F_GPIO38",
	"F_GPIO39",
	"F_GPIO40",
	"F_GPIO41",
	"F_GPIO42",
	"F_GPIO43",
	"F_GPIO44",
	"F_GPIO45",
	"F_GPIO46",
	"F_GPIO47",
	"F_GPIO48",
	"F_GPIO49",
	"F_GPIO50",
	"F_GPIO51",
	"F_GPIO52",
	"F_GPIO53",
	"F_GPIO54",
	"F_GPIO55",
	"F_GPIO56",
	"F_GPIO57",
	"F_GPIO58",
	"F_GPIO59",
	"F_GPIO60",
	"F_GPIO61",
	"F_GPIO62",
	"F_GPIO63",
	"F_GPIO64",
	"F_GPIO65",
	"F_GPIO66",
	"F_GPIO67",
	"F_GPIO68",
	"F_GPIO69",
	"F_GPIO70",
	"F_UART_TXD",
	"F_UART_RXD",
	"F_UART_CTS",
	"F_UART_RTS",
	"F_GPIO_LED1",
	"F_GPIO_LED2",
	"F_GPIO_LED3",
	"CSI0_RST_N",
	"CSI0_PWDN",
	"CSI0_PDB",
	"CSI0_INT",
	"CSI1_RST_N",
	"CSI1_PWDN",
	"CSI1_PDB",
	"CSI1_INT",
	"CSI2_RST_N",
	"CSI2_PWDN",
	"CSI2_PDB",
	"CSI2_INT",
	"CSI3_RST_N",
	"CSI3_PWDN",
	"CSI3_PDB",
	"CSI3_INT",
	"CSI4_RST_N",
	"CSI4_PWDN",
	"CSI4_PDB",
	"CSI4_INT",
	"CSI5_RST_N",
	"CSI5_PWDN",
	"CSI5_PDB",
	"CSI5_INT",
	"LTE_DISABLE_CTRL",
	"LTE_WAKE_AP",
	"M2_RTS_N",
	"F_SIO_GPO30",
	"CASE_OPEN_N",
	"F_SOC_COREPOWER_OK",
	"F_IGNITION",
};


/* Pin groups */

static const struct axonf_pingroup axonf_nxbox_pingroups[] = {
	AXONF_PINGROUP(F_GPIO01, F_GPIO01),
	AXONF_PINGROUP(F_GPIO02, F_GPIO02),
	AXONF_PINGROUP(F_GPIO03, F_GPIO03),
	AXONF_PINGROUP(F_GPIO04, F_GPIO04),
	AXONF_PINGROUP(F_GPIO05, F_GPIO05),
	AXONF_PINGROUP(F_GPIO06, F_GPIO06),
	AXONF_PINGROUP(F_GPIO07, F_GPIO07),
	AXONF_PINGROUP(F_GPIO08, F_GPIO08),
	AXONF_PINGROUP(F_GPIO09, F_GPIO09),
	AXONF_PINGROUP(F_GPIO10, F_GPIO10),
	AXONF_PINGROUP(F_GPIO11, F_GPIO11),
	AXONF_PINGROUP(F_GPIO12, F_GPIO12),
	AXONF_PINGROUP(F_GPIO13, F_GPIO13),
	AXONF_PINGROUP(F_GPIO14, F_GPIO14),
	AXONF_PINGROUP(F_GPIO15, F_GPIO15),
	AXONF_PINGROUP(F_GPIO16, F_GPIO16),
	AXONF_PINGROUP(F_GPIO17, F_GPIO17),
	AXONF_PINGROUP(F_GPIO18, F_GPIO18),
	AXONF_PINGROUP(F_GPIO19, F_GPIO19),
	AXONF_PINGROUP(F_GPIO20, F_GPIO20),
	AXONF_PINGROUP(F_GPIO21, F_GPIO21),
	AXONF_PINGROUP(F_GPIO22, F_GPIO22),
	AXONF_PINGROUP(F_GPIO23, F_GPIO23),
	AXONF_PINGROUP(F_GPIO24, F_GPIO24),
	AXONF_PINGROUP(F_GPIO25, F_GPIO25),
	AXONF_PINGROUP(F_GPIO26, F_GPIO26),
	AXONF_PINGROUP(F_GPIO27, F_GPIO27),
	AXONF_PINGROUP(F_GPIO28, F_GPIO28),
	AXONF_PINGROUP(F_GPIO29, F_GPIO29),
	AXONF_PINGROUP(F_GPIO30, F_GPIO30),
	AXONF_PINGROUP(F_GPIO31, F_GPIO31),
	AXONF_PINGROUP(F_GPIO32, F_GPIO32),
	AXONF_PINGROUP(F_GPIO33, F_GPIO33),
	AXONF_PINGROUP(F_GPIO34, F_GPIO34),
	AXONF_PINGROUP(F_GPIO35, F_GPIO35),
	AXONF_PINGROUP(F_GPIO36, F_GPIO36),
	AXONF_PINGROUP(F_GPIO37, F_GPIO37),
	AXONF_PINGROUP(F_GPIO38, F_GPIO38),
	AXONF_PINGROUP(F_GPIO39, F_GPIO39),
	AXONF_PINGROUP(F_GPIO40, F_GPIO40),
	AXONF_PINGROUP(F_GPIO41, F_GPIO41),
	AXONF_PINGROUP(F_GPIO42, F_GPIO42),
	AXONF_PINGROUP(F_GPIO43, F_GPIO43),
	AXONF_PINGROUP(F_GPIO44, F_GPIO44),
	AXONF_PINGROUP(F_GPIO45, F_GPIO45),
	AXONF_PINGROUP(F_GPIO46, F_GPIO46),
	AXONF_PINGROUP(F_GPIO47, F_GPIO47),
	AXONF_PINGROUP(F_GPIO48, F_GPIO48),
	AXONF_PINGROUP(F_GPIO49, F_GPIO49),
	AXONF_PINGROUP(F_GPIO50, F_GPIO50),
	AXONF_PINGROUP(F_GPIO51, F_GPIO51),
	AXONF_PINGROUP(F_GPIO52, F_GPIO52),
	AXONF_PINGROUP(F_GPIO53, F_GPIO53),
	AXONF_PINGROUP(F_GPIO54, F_GPIO54),
	AXONF_PINGROUP(F_GPIO55, F_GPIO55),
	AXONF_PINGROUP(F_GPIO56, F_GPIO56),
	AXONF_PINGROUP(F_GPIO57, F_GPIO57),
	AXONF_PINGROUP(F_GPIO58, F_GPIO58),
	AXONF_PINGROUP(F_GPIO59, F_GPIO59),
	AXONF_PINGROUP(F_GPIO60, F_GPIO60),
	AXONF_PINGROUP(F_GPIO61, F_GPIO61),
	AXONF_PINGROUP(F_GPIO62, F_GPIO62),
	AXONF_PINGROUP(F_GPIO63, F_GPIO63),
	AXONF_PINGROUP(F_GPIO64, F_GPIO64),
	AXONF_PINGROUP(F_GPIO65, F_GPIO65),
	AXONF_PINGROUP(F_GPIO66, F_GPIO66),
	AXONF_PINGROUP(F_GPIO67, F_GPIO67),
	AXONF_PINGROUP(F_GPIO68, F_GPIO68),
	AXONF_PINGROUP(F_GPIO69, F_GPIO69),
	AXONF_PINGROUP(F_GPIO70, F_GPIO70),
	AXONF_PINGROUP(F_UART_TXD, F_UART_TXD),
	AXONF_PINGROUP(F_UART_RXD, F_UART_RXD),
	AXONF_PINGROUP(F_UART_CTS, F_UART_CTS),
	AXONF_PINGROUP(F_UART_RTS, F_UART_RTS),
	AXONF_PINGROUP(F_GPIO_LED1, F_GPIO_LED1),
	AXONF_PINGROUP(F_GPIO_LED2, F_GPIO_LED2),
	AXONF_PINGROUP(F_GPIO_LED3, F_GPIO_LED3),
	AXONF_PINGROUP(CSI0_RST_N, CSI0_RST_N),
	AXONF_PINGROUP(CSI0_PWDN, CSI0_PWDN),
	AXONF_PINGROUP(CSI0_PDB, CSI0_PDB),
	AXONF_PINGROUP(CSI0_INT, CSI0_INT),
	AXONF_PINGROUP(CSI1_RST_N, CSI1_RST_N),
	AXONF_PINGROUP(CSI1_PWDN, CSI1_PWDN),
	AXONF_PINGROUP(CSI1_PDB, CSI1_PDB),
	AXONF_PINGROUP(CSI1_INT, CSI1_INT),
	AXONF_PINGROUP(CSI2_RST_N, CSI2_RST_N),
	AXONF_PINGROUP(CSI2_PWDN, CSI2_PWDN),
	AXONF_PINGROUP(CSI2_PDB, CSI2_PDB),
	AXONF_PINGROUP(CSI2_INT, CSI2_INT),
	AXONF_PINGROUP(CSI3_RST_N, CSI3_RST_N),
	AXONF_PINGROUP(CSI3_PWDN, CSI3_PWDN),
	AXONF_PINGROUP(CSI3_PDB, CSI3_PDB),
	AXONF_PINGROUP(CSI3_INT, CSI3_INT),
	AXONF_PINGROUP(CSI4_RST_N, CSI4_RST_N),
	AXONF_PINGROUP(CSI4_PWDN, CSI4_PWDN),
	AXONF_PINGROUP(CSI4_PDB, CSI4_PDB),
	AXONF_PINGROUP(CSI4_INT, CSI4_INT),
	AXONF_PINGROUP(CSI5_RST_N, CSI5_RST_N),
	AXONF_PINGROUP(CSI5_PWDN, CSI5_PWDN),
	AXONF_PINGROUP(CSI5_PDB, CSI5_PDB),
	AXONF_PINGROUP(CSI5_INT, CSI5_INT),
	AXONF_PINGROUP(LTE_DISABLE_CTRL, LTE_DISABLE_CTRL),
	AXONF_PINGROUP(LTE_WAKE_AP, LTE_WAKE_AP),
	AXONF_PINGROUP(M2_RTS_N, M2_RTS_N),
	AXONF_PINGROUP(F_SIO_GPO30, F_SIO_GPO30),
	AXONF_PINGROUP(CASE_OPEN_N, CASE_OPEN_N),
	AXONF_PINGROUP(F_SOC_COREPOWER_OK, F_SOC_COREPOWER_OK),
	AXONF_PINGROUP(F_IGNITION, F_IGNITION),
};



#endif /*__AXONFABRIC_NXBOX_PINS_H */
